### ISSUE TITLE
Support for kotlin multiplatform

### ISSUE THREAD

**Issue by achmadk** [dotenv-org/dotenv-vault-kotlin#6]
Hello. Thanks for creating this awesome library.

I recently created a mobile app with Kotlin multiplatform and then installed this library. Unfortunately, I got this error message like this:
![Screenshot 2024-10-11 104830](https://github.com/user-attachments/assets/712fadf7-7d98-4d7b-bdde-e02dd165e46d)
It seems that this library only supports Android.

I hope this issue will be resolved soon and this library supports other platforms like iOS, desktop, etc. Thanks.

**Comment by motdotla** [comment]
we actually have plans to deprecate this library. in it's place use [`dotenvx`](https://github.com/dotenvx/dotenvx)
